<?php
/**
 *  Kemana\AcceleratorBase\Block\HeaderElement $block
 */
$whishlistUrl = $block->getWhistlistUrl();
$_session=$block->getSession();

?>
<?php // @codingStandardsIgnoreStart ?>
<div class="block-mobile-addElement">
    <div class="block account-menu">
        <div class="account-menu_content" id="account-menu">
            <ul class="menu-content">
                <li class="main-item pg-club"><a href="<?= $this->getUrl('planet-gadget-club');  ?>"><?= __('Planet Club') ?></a></li>
                <li class="main-item pg-track"><a href="<?= $this->getUrl('sales/order/history'); ?>"><?= __('Track') ?></a></li>
                <?php if (!$_session->isLoggedIn()): ?>
                    <li class="main-item account-login"><a href="<?= $this->getUrl('customer/account/login'); ?>"><?=
                            __('My Account') ?></a></li>
                <?php elseif ($_session->isLoggedIn()): ?>
                    <li class="main-item account-login"><a href="<?= $this->getUrl('customer/account/login'); ?>"><?=
                            __('My Account') ?></a>
                    <ul>
                        <li class="main-item-child"><a href="<?= $this->getUrl('customer/account/index'); ?>"><?= __('Dashboard') ?></a></li>
                        <li class="main-item-child"><a href="<?= $this->getUrl('sales/order/history/'); ?>"><?= __('Order History') ?></a></li>
                        <li class="main-item-child"><a href="<?= $this->getUrl('wishlist'); ?>"><?= __('Wishlist ') ?></a></li>
                        <li class="main-item-child"><a href="<?= $this->getUrl('customer/address/'); ?>"><?= __('Address Book') ?></a></li>
                        <li class="main-item-child"><a href="<?= $this->getUrl('customer/account/logout'); ?>"><?= __('Logout') ?></a></li>
                    </ul>
                    </li>
                <?php endif; ?>
            </ul>
            <ul class="menu-content-2">
                <li class="main-item"><a href="<?= $this->getUrl('bank-promotion'); ?>"><?= __('Bank Promo') ?></a></li>
                <li class="main-item"><a href="<?= $this->getUrl('trade-in-plus'); ?>"><?= __('Trade-In Plus') ?></a></li>
                <li class="main-item"><a href="<?= $this->getUrl('store-locations'); ?>"><?= __('Store Locator') ?></a></li>
                <?= $block->getBlockHtml('catalog.compare.link'); ?>
                <li class="main-item"><?= $block->getBlockHtml('top-line-right'); ?></li>
            </ul>

        </div>
    </div>
</div>

<?php // @codingStandardsIgnoreEnd ?>
