<?php
/**
 *  Kemana\AcceleratorBase\Block\HeaderElement $block
 */
/** @var \Kemana\AcceleratorBase\Helper\Data $kemanaAcceleratorBaseHelper */
$kemanaAcceleratorBaseHelper = $this->helper(Kemana\AcceleratorBase\Helper\Data::class);
$currency = $kemanaAcceleratorBaseHelper->getCurrentCurrencyCode();
$storeManager = $kemanaAcceleratorBaseHelper->getStoreManager();
// @codingStandardsIgnoreStart
?>

<div class="language-currency-wrapper">
    <div class="language-currency-block">
        <span class="language-flag"></span>
        <span class="language"><?= substr($block->escapeHtml($storeManager->getStore()->getName()), 0, 2) ?></span>
        <i class="fa fa-caret-down"></i>
    </div>
    <div class="language-currency-dropdown">
        <?= $block->getChildHtml("store_language"); ?>
        <?= $block->getChildHtml("store_currency"); ?>
    </div>
</div>

