<?php
/**
 * Kemana_Banner
 * @author Gayan Thrimanne<gthrimanne@kemana.com>
 * @see README.md
 *
 */

/** @var \Kemana\Banner\Block\Slider $block */

use Kemana\Banner\Model\Config\Source\Type;

$banners = $block->getBannerCollection();
if (count($banners)) : ?>
    <?php
    $sliderId = $block->getSliderId() . uniqid('-', false);
    $sliderOptions = $block->getBannerOptions(); ?>
    <div class="carousel-container">
        <div id="banner-slider-carousel">
            <?php $iterator = 1; ?>
            <div id="bannerslider-list-items-<?= $sliderId; ?>"
                 class="<?= count($banners) > 1 ? 'owl-carousel owl-theme' : 'single-slide'?>">
                <?php foreach ($banners as $banner) : ?>
                    <?php
                    $bnType = $banner->getType();
                    $bnTitle = $banner->getTitle();
                    $bnUrl = $banner->getUrlBanner();
                    $bnImg = $banner->getImageUrl();
                    $bnImgMobile = $banner->getImageMobileUrl();
                    ?>
                    <?php if (($bnType === Type::CONTENT && empty($banner->getContent())) || ($bnType === Type::IMAGE && empty($banner->getImage()))) : continue; ?>
                    <?php endif; ?>
                    <?= ($iterator++ === 1) ? '<div class="banner-item banner-slider">' : '</div><div class="banner-item banner-slider">' ?>
                    <?php if ($bnType === Type::CONTENT) : ?>
                        <div class="item-content">
                            <?= $block->getPageFilter($banner->getContent()); ?>
                        </div>
                    <?php else : #image type?>
                        <div class="item-image">
                            <?php if (!empty($bnUrl)) : ?>
                                <a class="owl-image"
                                   href="<?= $bnUrl ?>" <?= ($banner->getNewtab() === '1') ? 'target="_blank"' : '' ?>>
                                    <?php if (!empty($bnTitle)) : ?>
                                        <div class="banner-title"><?= $bnTitle ?></div>
                                    <?php endif; ?>
                                    <img class="img-responsive desktop" src="<?= $bnImg ?>">
                                    <img class="img-responsive mobile" src="<?= $bnImgMobile ?>">
                                </a>
                            <?php else : ?>
                                <img class="owl-image img-responsive desktop" src="<?= $bnImg ?>"
                                     title="<?= $bnTitle ?>">
                                <img class="owl-image img-responsive mobile" src="<?= $bnImgMobile ?>"
                                     title="<?= $bnTitle ?>">
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <?= ($iterator === count($banners) + 1) ? '</div>' : '' ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?= $block->getPagerHtml() ?>
    </div>
    <?php if (count($banners) > 1) : ?>
        <script>
            require(['jquery', 'owl.carousel'], function ($) {
                $('#bannerslider-list-items-<?= $sliderId; ?>').owlCarousel(<?= $sliderOptions; ?>);
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
