<?php
/**
 * Copyright © 2022 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_Common
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   Parth Godhani <pgodhani@kemana.com>
 */
?>

<?php
/** @var \Kemana\AcceleratorBase\Helper\Data $kemanaAcceleratorBaseHelper */
$kemanaAcceleratorBaseHelper = $this->helper(Kemana\AcceleratorBase\Helper\Data::class);
?>
<div class="order-date">
    <?= $block->escapeHtml(__('<span class="label">Order Date</span> %1', '<date> : ' . $kemanaAcceleratorBaseHelper->formatDate(strtotime($block->getOrder()->getCreatedAt()), "d M Y") . '</date>'), ['span', 'date']) ?>
</div>
