<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="block block-dashboard-orders">
<?php
    /** @var \Kemana\AcceleratorBase\Helper\Data $kemanaAcceleratorBaseHelper */
    $kemanaAcceleratorBaseHelper = $this->helper(Kemana\AcceleratorBase\Helper\Data::class);
    $_orders = $block->getOrders();
    $count = count($_orders);
?>
    <div class="block-title order">
        <strong><?= $block->escapeHtml(__('ORDER HISTORY')) ?></strong>
        <?php if ($count > 0) : ?>
            <a class="action view" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
    <?= $block->getChildHtml() ?>
    <?php if ($count > 0) : ?>
        <div class="table-wrapper orders-recent">
            <table class="data table table-order-items recent" id="my-orders-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('ORDER HISTORY')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Order')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                        <th scope="col" class="col ship_to"><?= $block->escapeHtml(__('Ship To')) ?></th>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Total')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col actions"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($_orders as $_order) :
                            $shipTo = '';
                            if(!empty($_order->getShippingAddress())){
                                $shipTo = $_order->getShippingAddress()->getName();
                            }else{
                                $shipTo = $_order->getBillingAddress()->getName();
                            }
                        ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Order')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= $block->escapeHtml($kemanaAcceleratorBaseHelper->formatDate($_order->getCreatedAt(),"d M Y")) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="col ship_to"><?= $block->escapeHtml($shipTo) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                                <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                    <span><?= $block->escapeHtml(__('Detail')) ?></span>
                                </a>
                                <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)
                                    ->canReorder($_order->getEntityId())
                                ) : ?>
                                    <a href="#" data-post='<?= /* @noEscape */
                                    $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                        ->getPostData($block->getReorderUrl($_order))
                                    ?>' class="action order">
                                        <span><?= $block->escapeHtml(__('Re-Order')) ?></span>
                                    </a>
                                <?php endif ?>

                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else : ?>
        <div class="message info empty"><span><?= $block->escapeHtml(__('No order history')) ?></span></div>
    <?php endif; ?>
    </div>
</div>
