<?php
/**
 * Copyright © 2021 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_AcceleratorBase
 * @license  Proprietary
 *
 * @author   Anton Vinoj <avinoj@kemana.com>
 */
?>
<div class="cms-main-container">
    <?= $block->getChildHtml('home-page-new-arrivals') ?>
    <?= $block->getChildHtml('home-page-how-it-works') ?>
    <?= $block->getChildHtml('home-page-inner-banner') ?>
    <?= $block->getChildHtml('home-page-bestsellers') ?>
    <?= $block->getChildHtml('homepage_flash_sale_deal_content') ?>
    <?= $block->getChildHtml('home-page-recently-viewed-products') ?>
    <?= $block->getChildHtml('home-page-full-width-banner') ?>
</div>
