<?php

/**  <div class="post-list-item col-mp<?= $block->isGridView() ? ' post-item-grid mp-6 mp-xs-12' : ' post-item-list mp-12'; ?>">
*/
/** @var \Kemana\BlogArticle\Block\Frontend $block */
?>
<div class="post-list-content" id="mpblog-list-container">
    <?php $postCollection = $block->getPostCollection(); ?>
    <?php if ($postCollection && $postCollection->getSize()): ?>
        <div class="post-list-body">
            <?php $i = 1 ?>
            <?php /** @var \Kemana\Blog\Model\Post $post */
            foreach ($postCollection as $post): ?>
                <div class="post-list-item col-xs-12 col-mp<?= $block->isGridView() ? ' post-item-grid mp-6 mp-xs-12' : ' post-item-list mp-12'; ?>">
                    <div class="post-item-wrapper">
                        <?php if ($post->getImage()): ?>
                            <div class="post-image">
                                <a href="<?= $post->getUrl() ?>">
                                    <img class="img-responsive"
                                         src="<?= $block->getImageUrl($post->getImage()); ?>"
                                         alt="<?= $block->escapeHtml($post->getName()); ?>"/>
                                </a>
                            </div>
                        <?php endif; ?>
                        <div class="post-info-wrapper">
                            <h2 class="mp-post-title">
                                <a class="post-link-title" title="<?= $block->escapeHtml($post->getName()); ?>"
                                   href="<?= $post->getUrl() ?>">
                                    <?= $post->getName(); ?>
                                </a>
                            </h2>
                            <div class="post-short-description">
                                <?= $block->maxShortDescription($post->getShortDescription()); ?>
                            </div>
                            <div class="mp-post-info">
                                <?= $block->getPostInfo($post); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php $postdata = $post ?>
            <?php endforeach; ?>
            <div class="mp-clear"></div>
        </div>
        <?= $block->getPagerHtml() ?>
    <?php else: ?>
        <?= $block->escapeHtml(__('There are no posts at this moment')); ?>
    <?php endif; ?>
    <?= $this->getChildHtml('additional'); ?>
</div>
<?php if ($author = $block->getAuthor()): ?>
    <script>
        require(['jquery'], function($){
            $('.page-title-wrapper').html(`
            <div class="row">
                <div class="col-2">
                    <img src="<?= ($author->getImage()) ? $block->resizeImage($author->getImage(), '200x', \Kemana\Blog\Helper\Image::TEMPLATE_MEDIA_TYPE_AUTH) : $block->getDefaultAuthorImage(); ?>" class="photo-prof">
                </div>
                <div class="col">
                    <h1 class="page-title"><span class="base" data-ui-id="page-title-wrapper"><?= $author->getName() ?></h1>
                    <br>
                    <?= $author->getShortDescription(); ?>
                </div>
            </div>
            `);
        });
    </script>
<?php endif; ?>
