<?php
/**
 * Copyright © 2022 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_Jobs
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Kristian Claridad <kclaridad@kemana.com>
 */

/** @var \Kemana\Jobs\Block\Adminhtml\Applications\Edit\AdditionalFilePath $block */
?>
<?php $dataCodeEdit   = $block->getAdditionalFilePath('id_card_file'); ?>
<?php if (!empty($dataCodeEdit)) : ?>
<div class="admin__fieldset-wrapper-content admin__fieldset">
    <div class="admin__field  form-control">
        <label class="admin__field-label">
            <span><?= __('ID Card')?></span>
        </label>
        <div class="admin__field-control _required">
            <a href="<?php echo $dataCodeEdit ?>">
                <button><?= __('Click to Download ID Card')?></button>
            </a>
        </div>
    </div>
</div>
<?php endif;?>
