<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Register New Account')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?= $block->escapeHtml(__('Register an account and get various benefits such as:')) ?></p>
        <div class="new-customer-benefits">
            <ul>
                <li><?= $block->escapeHtml(__('Membership Gold Planet Gadget Club')) ?></li>
                <li><?= $block->escapeHtml(__('Faster Checkout Process')) ?></li>
                <li><?= $block->escapeHtml(__('Save multiple shipping addresses')) ?></li>
                <li><?= $block->escapeHtml(__('View and track orders')) ?></li>
                <li><?= $block->escapeHtml(__('View order history')) ?></li>
            </ul>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
