<!--
/**
 * Copyright © 2022 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Magento_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Parth Godhani <pgodhani@kemana.com>
 */
-->
<script>
	require(['jquery'], function($){ 
		$(window).load(function() {
			let phonenumber = "<?= $block->getPhonenumber() ? $block->getPhonenumber() : ''?>",
				redirectUrl = "<?= $block->getRedirectionUrl() ?>",
				currentUrl = window.location.href;

			if(phonenumber.indexOf("62000000000") != -1 && currentUrl.indexOf("customer/account/edit") == -1){
				window.location.href = "<?= $block->getRedirectionUrl()?>";
			}
		});
 	});
</script>