<?php
/**
 * Copyright © 2022 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_Pcp
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Achintha Madushan <amadushan@kemana.com>
 */

?>
<?php
/** @var \Kemana\Pcp\Block\Category $block */

$bannerID = $block->getCategoryBannerId()

?>
<?php if ($bannerID): ?>
    <?= $block->getLayout()->createBlock(\Kemana\Banner\Block\Widget::class)->setSliderId($bannerID)->toHtml(); ?>
<?php endif; ?>
