<?php
/**
 * Copyright © 2022 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_Pcp
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Achintha Madushan <amadushan@kemana.com>
 */

/** @var \Kemana\Pcp\Block\Category $block */

$subCategories = $block->prepareSubCategoryData();
?>

<?php if (count($subCategories)): ?>
<div class="pcp-sub-categories">
    <?php foreach ($subCategories as $category): ?>
        <?php if ($category['name']): ?>
            <div><?= $category['name'] ?></div>
        <?php endif; ?>

        <?php if ($category['shortDescription']): ?>
            <div><?= $category['shortDescription'] ?></div>
        <?php endif; ?>

        <?php if ($category['image']): ?>
            <div>
                <image src="<?= rtrim($block->getUrl(), "/") . $category['image'] ?>" alt="<?= $category['name'] ?>"/>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>
</div>

