<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>

<?php if (count($block->getStores()) > 1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <?php foreach ($block->getStores() as $_lang): ?>
       <?php if ($_lang->getId() == $block->getCurrentStoreId()) { ?>
        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option active">
            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                <?= $block->escapeHtml($_lang->getName()) ?>
            </a>
        </li>
    <?php }else{ ?>
        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                <?= $block->escapeHtml($_lang->getName()) ?>
            </a>
        </li>
   <?php  } ?>
    <?php endforeach; ?>
<?php endif; ?>
