<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */

/** @var $viewModel \Kemana\Catalog\ViewModel\Product\View */

$viewModel = $block->getViewModel();

?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                if ($name == 'related.post.tab') {
                    continue;
                }
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data-block">
                    <div class="data item title"
                         data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="trigger"
                           href="#<?= $block->escapeUrl($alias) ?>"
                           id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                            <?= /* @noEscape */ $label ?>
                        </a>
                    </div>
                    <div class="data item content"
                         aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                        <?= /* @noEscape */ $html ?>
                    </div>
                </div>
            <?php endforeach;?>
            <div class="data-block-warranty">
            <div class="data item title"
                 data-role="collapsible" id="tab-label-warranty">
                <a class="data switch"
                   tabindex="-1"
                   data-toggle="trigger"
                   href="#<?= $block->escapeUrl('warranty') ?>"
                   id="tab-label-<?= $block->escapeHtmlAttr('warranty') ?>-title">
                    <?= /* @noEscape */ __('Warranty') ?>
                </a>
            </div>
            <div class="data item content"
                 aria-labelledby="tab-label-<?= $block->escapeHtmlAttr('warranty') ?>-title" id="<?= $block->escapeHtmlAttr('warranty') ?>" data-role="content">
                <?= /* @noEscape */ $viewModel->getWarrantyForCurrentProduct(); ?>
            </div>
            </div>
        </div>
    </div>
<?php endif; ?>
