<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
/** @var \Kemana\AcceleratorBase\Helper\ProductImage $kemanaAcceleratorBaseImageHelper */
$kemanaAcceleratorBaseImageHelper = $this->helper(Kemana\AcceleratorBase\Helper\ProductImage::class);

$_item = $block->getItem();
$imageHelper  = $this->helper('Magento\Catalog\Helper\Image');
$image_url = $imageHelper->init($_item->getProduct(), 'thumbnail', ['type'=>'thumbnail'])->keepAspectRatio(true)->resize('135', '135')->getUrl();
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <div class="image"><img src="<?= $image_url ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"></div>
        <div class="item-details">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()) : ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <?php if (!$block->getPrintStatus()) : ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd>
                        <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                            <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                        <?php else : ?>
                            <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                        <?php endif; ?>
                    </dd>
                <?php else : ?>
                    <dd>
                        <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        </div>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) : ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
            <li class="item">
                <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
