<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<div class="error-page">
    <div class="error-page-wrapper">
        <div class="error-page-top">
            <a href="#" class="logo"><img src="images/logo-error.svg"></a>
            <div class="error-page-title">
                <h1>There has been an error processing your request</h1>
                <?php if ($this->reportId): ?>
                    <p>Error log record number: <span><?= $this->reportId ?></span></p>
                <?php endif; ?>
            </div>
            <?php if ($this->showSentMsg): ?>
            <div class="message success message-success">
                <div>Your message was submitted and will be responded as soon as possible. Thank you for reporting.</div>
            </div>
            <?php endif; ?>
            <?php if ($this->showSendForm): ?>
            <div class="message info message-info">
                <div>
                    We are currently experiencing some technical issue. We apologize for the inconvenience and will contact you shortly to resolve the issue. To help us serve you better, please fill the form below.
                </div>
            </div>
                <?php if ($this->showErrorMsg): ?>
            <div class="message error message-error">
                <div>
                    Please fill all required fields with valid information
                </div>
            </div>
                <?php endif; ?>
        </div>
        <form action="<?= "{$this->getBaseUrl(true)}errors/report.php?id={$this->reportId}" ?>" method="post" id="form-validate" class="form">
            <fieldset class="fieldset" data-hasrequired="* Required Fields">
                <legend class="legend"><span>Personal Information</span></legend>
                <div class="field firstname required">
                    <label for="firstname" class="label">First Name</label>
                    <div class="control">
                        <input type="text" name="firstname" placeholder="Enter your first name" id="firstname" value="" title="First Name" class="required-entry input-text" />
                    </div>
                </div>
                <div class="field lastname required">
                    <label for="lastname" class="label">Last Name</label>
                    <div class="control">
                        <input type="text" name="lastname" placeholder="Enter your last name" id="lastname" value="" title="Last Name" class="required-entry input-text" />
                    </div>
                </div>
                <div class="field email required">
                    <label for="email_address" class="label">Email</label>
                    <div class="control">
                        <input type="text" name="email" placeholder="Enter your email address" id="email_address" value="" title="Email Address" class="validate-email required-entry input-text" />
                    </div>
                </div>
                <div class="field telephone">
                    <label for="telephone" class="label">Phone Number</label>
                    <div class="control">
                        <input type="text" name="telephone" placeholder="Enter your phone number" id="telephone" value="" title="Telephone" class="input-text" />
                    </div>
                </div>
                <div class="field comment">
                    <label for="comment" class="label">Message</label>
                    <div class="control">
                        <textarea name="comment" cols="5" rows="3" placeholder="Enter your message" class="textarea"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <button name="submit" class="action primary" type="submit"><span>Submit</span></button>
            </div>
        </form>
        <?php elseif ('' == $this->reportAction): ?>
            <p><em>Exception printing is disabled by default for security reasons.</em></p>
        <?php endif; ?>

        <?php if ($this->reportAction == 'print'): ?>
        <div class="trace-container">
            <div class="trace">
                <pre><?= htmlspecialchars($this->reportData[0]) ?></pre>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
