<?php
/**
 * Copyright © 2021 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_Promotion
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Achintha Madushan <amadushan@kemana.com>
 */

/**
 * @var \Kemana\Promotion\Block\Promotion\Promotion $block
 */

$promotion = $block->getPromotionById();

?>

<div class="promotion-detail">
    <div class="title">
        <h1><?= __($promotion->getTitle()) ?></h1>
    </div>
    <div class="content">
        <?php if ($promotion->getContent()): ?>
        <?= /* @noEscape */ $block->processContent($promotion->getContent()) ?>
        <?php endif; ?>
    </div>
</div>
