<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('ADDRESS BOOK')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $block->escapeHtml(__('Set Addresses')) ?></span></a>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Main Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                    <br>
                    <?php
                        $billingMapPoint = $block->getPrimaryBillingAddressMapPoint();
                    ?>
                    <span class="map-point-label <?= ($billingMapPoint === 'Already Pinpoint') ? 'active' : ''?>">
                        <?= $block->escapeHtml(__($billingMapPoint)) ?>
                    </span>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Main Shipping Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                    <br>
                    <?php
                        $shippingMapPoint = $block->getPrimaryShippingAddressMapPoint();
                    ?>
                    <span class="map-point-label <?= ($shippingMapPoint === 'Already Pinpoint') ? 'active' : ''?>">
                        <?= $block->escapeHtml(__($shippingMapPoint)) ?>
                    </span>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
            </div>
        </div>
    </div>
</div>
