<?php

?>
<?php
/** @var \Kemana\Blog\Block\Adminhtml\Category\Edit\Form $block */
$parentId = $block->getParentCategoryId();
$categoryId = $block->getCategoryId();

$blockGrid = $block->getLayout()->getBlock('kemana_blog_category_edit_tab_post');
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<div data-mage-init='{"floatingHeader": {}}' class="page-actions">
    <?= $block->getAdditionalButtonsHtml(); ?>
</div>
<?= $block->getTabsHtml() ?>

<iframe name="iframeSave" style="display:none; width:100%;"
        src="<?= $block->getViewFileUrl('blank.html') ?>"></iframe>
<form id="category_edit_form" name="category-edit-form" action="<?= $block->getSaveUrl() ?>" method="post"
      enctype="multipart/form-data">
    <div class="no-display">
        <input type="hidden" name="isIframe" value="1"/>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>
        <input type="hidden" name="active_tab_id" id="active_tab_id" value=""/>
        <?php if ($parentId !== 0): ?>
            <input type="hidden" name="parent" value="<?= $parentId; ?>"/>
        <?php endif; ?>
        <?php if ($categoryId !== 0): ?>
            <input type="hidden" name="category_id" value="<?= $categoryId; ?>"/>
        <?php endif; ?>
        <input type="hidden" name="selected_products" id="in_category_products" value=""/>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Catalog/catalog/category/assign-products": {
                        "selectedProducts": <?= $block->getPostsJson(); ?>,
                        "gridJsObjectName": <?= '"' . $gridJsObjectName . '"' ?: '{}'; ?>
                    }
                }
            }

        </script>
    </div>
    <div id="category_tab_content"></div>
</form>

<div data-id="information-dialog-category" class="messages" style="display: none;">
    <div class="message message-notice">
        <div><?= $block->escapeHtml(__('This operation can take a long time')); ?></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "categoryEditForm": {
                "refreshUrl": "<?= $block->getRefreshPathUrl();?>"
            }
        }
    }
</script>
<script>
    <?php if ($block->isAjax() && ($tabsBlock = $block->getLayout()->getBlock('tabs')) && ($_tabsJsObject = $tabsBlock->getJsObjectName())): ?>
    // Temporary solution, will be replaced after refactoring of manage category functionality
        <?php $tabsBlock = $block->getLayout()->getBlock('tabs'); ?>
    require(["jquery", "mage/backend/tabs"], function ($) {
        var activeAnchor = $('#<?= $tabsBlock->getId() ?>').tabs('activeAnchor');
        if (activeAnchor.length) {
            $('active_tab_id').value = activeAnchor.prop('id');
        }
        $('active_tab_id').tabsJsObject = $('#<?= $tabsBlock->getId() ?>');
    });
    <?php endif; ?>
</script>
