<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */

/** @var \Kemana\Labelmanager\Helper\Data $kemanaLabelmanagerHelper */
$kemanaLabelmanagerHelper = $this->helper(Kemana\Labelmanager\Helper\Data::class);
?>
<?php $total = $block->getItems()->getSize() ?>
<?php if ($total) :?>
  
    <div class="table-wrapper comparison">
        <table class="data table table-comparison" id="product-comparison"
               data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Compare Products')) ?></caption>
            <tbody>
            <tr>
                <?php if ($kemanaLabelmanagerHelper->isShowLabelsOnCompareProducts()) : ?>
                    <div id="ns-label-loader" data-mage-init='{"nsLabels": {
                     "id": false,
                    "location":"inner",
                    "baseUrl": "<?= $block->getBaseUrl() ?>",
                    "currency": "<?= $kemanaLabelmanagerHelper->getCurrencySymbol() ?>"}}'></div>
                <?php endif; ?>
                <?php $index = 0; ?>
                <?php $helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $item) :?>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="cell product product-item info">
                        <div class="product-item-wrapper">
                            <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                            <div class="compare-product-item-actions hidden-print">
                                <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow()) :?>
                                    <a href="#"
                                        data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item) ?>'
                                        class="action towishlist"
                                        data-action="add-to-wishlist">
                                        <span><?= __('Add to wishlist')?></span>
                                    </a>
                                <?php endif; ?>
                                    <a href="#" data-post='<?= /* @noEscape */ $compareHelper->getPostDataRemove($item) ?>'
                                        class="action delete" title="<?= $block->escapeHtmlAttr(__('Remove Product')) ?>">
                                        <span><?= __('Remove')?></span>
                                    </a>
                            </div>
                            <a class="product-item-photo"
                            href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                            title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                            </a>
                            <strong class="product-item-name">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                    <?= /* @noEscape */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= /* @noEscape */ $block->getProductPrice($item, '-compare-list-top') ?>
                            <div class="product-item-actions hidden-print">
                                <div class="actions-primary">
                                    <?php if ($item->isSaleable()) :?>
                                        <form data-role="tocart-form"
                                            action="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product\Compare::class)->getAddToCartUrl($item)) ?>"
                                            method="post">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit" class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else :?>
                                        <?php if ($item->getIsSalable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            </tbody>
            <tbody>
            <tr>
                <?php $indexO = 0; ?>
                <?php foreach ($block->getItems() as $item) :?>
                    <?php if ($index++ == 0) :?>
                        <th scope="row" class="cell label">
                            <span class="attribute label">Evaluation</span>
                        </th>
                    <?php endif; ?>
                        <td class="cell product attribute">
                            <?= ($block->getReviewsSummaryHtml($item, 'short') ? $block->getReviewsSummaryHtml($item, 'short') : '<span>N/A</span>') ?>
                        </td>
                <?php endforeach; ?>
            </tr>
            <?php foreach ($block->getAttributes() as $attribute) :?>
                <?php $index = 0; ?>
                <?php if ($block->hasAttributeValueForProducts($attribute)) :?>
                    <tr>
                        <?php foreach ($block->getItems() as $item) :?>
                            <?php if ($index++ == 0) :?>
                                <th scope="row" class="cell label">
                                    <span class="attribute label">
                                        <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                    </span>
                                </th>
                            <?php endif; ?>
                            <td class="cell product attribute">
                                <div class="attribute value">
                                    <?php switch ($attribute->getAttributeCode()) {
                                        case "price": ?>
                                            <?=
                                            /* @noEscape */ $block->getProductPrice(
                                                $item,
                                                '-compare-list-' . $attribute->getCode()
                                            )
                                            ?>
                                            <?php break;
                                        case "small_image": ?>
                                            <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                            <?php break;
                                        default :?>
                                            <?php if (is_string($block->getProductAttributeValue($item, $attribute))) :?>
                                                <?= /* @noEscape */ $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                            <?php else : ?>
                                                <?=  $block->escapeHtml($helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode())) ?>
                                            <?php endif; ?>
                                            <?php break;
                                    } ?>
                                </div>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
    <?php endif; ?>
<?php else :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('You have no items to compare.')) ?></div></div>
<?php endif; ?>
