<?php
/**
 * Copyright © 2020 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_SocialLogin
 * @license  Proprietary
 *
 * @author   Aranga Wijesooriya <awijesooriya@kemana.com>
 */

$availableSocials = $block->getAvailableSocials();
$childBlock = $block->getChildBlock('request.info');

if ($block->canShow() && sizeof($availableSocials)) :
    ?>
    <div class="account-social-login-title"><span><?= $escaper->escapeHtml(__('or'))?></span></div>
    <div class="block social-login-authentication-channel account-social-login">
        <div class="block-content">
            <?php foreach ($availableSocials as $key => $social) : ?>
                <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $key ?>-login">
                    <a class="btn btn-block btn-social btn-<?= $block->getBtnKey($key) ?>"
                       data-mage-init='{"socialProvider": {"url": "<?= $social['login_url'] ?>", "label": "<?= $escaper->escapeHtml(__('Login By %1', $social['label'])) ?>"}}'>
                        <span class="fa fa-<?= $block->getBtnKey($key) ?>"></span>
                        <?= $escaper->escapeHtml(__('Login with %1', $social['label'])) ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php if ($childBlock->isRequireMoreInfo()) : ?>
    <div id="social-login-popup" class="white-popup mfp-with-anim mfp-hide"
         data-mage-init='{"Kemana_SocialLogin/js/popup":<?= $childBlock->getFormParams() ?>}'>
        <?= $block->getChildHtml('request.info') ?>
    </div>
<?php endif; ?>
<style type="text/css">
    .request-popup{
        overflow-y: unset;
        max-width: 800px;
        left: 30%;
    }
    .request-popup .modal-header{
        padding: 0;
    }
    .request-popup .modal-header button.action-close{
        color: white;
        z-index: 100;
    }
    .request-popup .modal-content{
        padding: 0;
    }
</style>
