<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

/** @var \Kemana\AcceleratorBase\Helper\Data $kemanaAcceleratorBaseHelper */
$kemanaAcceleratorBaseHelper = $this->helper(Kemana\AcceleratorBase\Helper\Data::class);
$qtyDropDown = $kemanaAcceleratorBaseHelper->isEnableQtyDropDown();
$qtyCount = $kemanaAcceleratorBaseHelper->getQtyCount();

/** @var \Kemana\Checkout\Helper\Data $kemanaCheckout */
$kemanaCheckout = $this->helper(Kemana\Checkout\Helper\Data::class);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) :?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else :?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
        </a>
    <?php else :?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) :?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) :?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                            <?php else :?>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <?php if ($canApplyMsrp) :?>
        <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else :?>
        <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty <?=$product->getChildId()?>" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <?php
        if ($kemanaCheckout->getStockStatus($product, $_options)):?>
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                        <?php if (!$qtyDropDown): ?>

                            <a class="alo_qty alo_qty_dec ajax-cart-qty-minus" href="javascript:void(0)"></a>
                            <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                                name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                                data-cart-item-id="<?= /* @escapeNotVerified */ $_item->getSku() ?>"
                                value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                                type="number"
                                size="4"
                                title="<?= $block->escapeHtml(__('Qty')); ?>"
                                class="input-text qty"
                                maxlength="12"
                                data-validate="{required:true,'validate-greater-than-zero':true}"
                                data-role="cart-item-qty"/>
                            <a class="alo_qty alo_qty_inc ajax-cart-qty-plus" href="javascript:void(0)"></a>

                        <?php else: ?>
                        <input type="hidden" id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                            name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                            data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                            title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                            class="qty-input"
                            data-validate="{required:true,'validate-greater-than-zero':true}"
                            data-role="cart-item-qty"/>

                        <ul class="qty-selector" data-mage-init='{"customDropDown":{"ajax":true}}'>
                            <li class="item-main" data-item="<?= $block->escapeHtmlAttr($block->getQty()) ?>">
                                <?= $block->escapeHtmlAttr($block->getQty()) ?>
                            </li>
                            <ul class="qty-selector-dropdown" style="display: none">
                                <?php
                                for ($qty = 1; $qty <= $qtyCount; $qty++) { ?>
                                    <li class="item" data-item="<?= $qty ?>">
                                        <?= $qty ?>
                                    </li>
                                <?php } ?>
                            </ul>
                        </ul>
                        <?php endif; ?>
                    </label>
                </div>
            </div>
        <?php else:?>
            <div class="pg-checkout-out-of-stock">
                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
            </div>
        <?php endif; ?>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="4">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>
