<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Files.LineLength

?>

<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="block block-reward-membership-container">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('BENEFIT MEMBERSHIP')) ?></strong>
    </div>
    <div class="block-content">
        <div class="block-reward-membership block-reward-gold-membership">
            <h4 class="block-header block-header-gold">
                <span><?= $block->escapeHtml(__('Gold Member')) ?></span>
            </h4>
            <ul class="gold-membership-ul-wrapper">
                <li><?= $block->escapeHtml(__('Earn points for every purchase')) ?></li>
                <li><?= $block->escapeHtml(__('Service discount at the nearest Planet Gadget')) ?></li>
                <li><?= $block->escapeHtml(__('Free parking at the nearest Planet Gadget Store')) ?></li>
                <li><?= $block->escapeHtml(__('Merchant Partner Discount')) ?></li>
                <li><?= $block->escapeHtml(__('Dapatkan penawaran produk terbaru')) ?></li>
                <li><?= $block->escapeHtml(__('Discounts for purchasing accessories')) ?></li>
                <li><?= $block->escapeHtml(__('Exchange member points')) ?></li>
            </ul>
        </div>
        <div class="block-reward-membership block-reward-premium-membership">
            <h4 class="block-header  block-header-premium">
                <span><?= $block->escapeHtml(__('Premium Member')) ?></span>
            </h4>
            <ul class="gold-membership-ul-wrapper">
                <li><?= $block->escapeHtml(__('Earn points for every purchase')) ?></li>
                <li><?= $block->escapeHtml(__('Service discount at the nearest Planet Gadget')) ?></li>
                <li><?= $block->escapeHtml(__('Free parking at the nearest Planet Gadget Store')) ?></li>
                <li><?= $block->escapeHtml(__('Merchant Partner Discount')) ?></li>
                <li><?= $block->escapeHtml(__('Dapatkan penawaran produk terbaru')) ?></li>
                <li><?= $block->escapeHtml(__('Discounts for purchasing accessories')) ?></li>
                <li><?= $block->escapeHtml(__('Exchange member points')) ?></li>
                <li><?= $block->escapeHtml(__('Earn points on your birthday')) ?></li>
                <li><?= $block->escapeHtml(__('Free Shipping')) ?></li>
                <li><?= $block->escapeHtml(__('Enjoy Priority Lounge facilities at the nearest Planet Gadget Store')) ?></li>
            </ul>
        </div>
    </div>
</div>
