<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Files.LineLength

?>

<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="block block-reward-membership-container">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('BENEFIT MEMBERSHIP')) ?></strong>
    </div>
    <div class="block-content">
        <div class="block-reward-membership block-reward-gold-membership">
            <h4 class="block-header block-header-gold">
                <span><?= $block->escapeHtml(__('Gold Member')) ?></span>
            </h4>
            <ul class="gold-membership-ul-wrapper">
                <li><?= $block->escapeHtml(__('Transaksi < Rp10.000.000')) ?></li>
                <li><?= $block->escapeHtml(__('Birthday Rewards (bonus hingga 50.000 points)')) ?></li>
                <li><?= $block->escapeHtml(__('Diskon Aksesoris Up To 5%')) ?></li>
                <li><?= $block->escapeHtml(__('Membership Baru (Bonus 20.000 points)')) ?></li>
                <li><?= $block->escapeHtml(__('Berlaku 2 Tahun')) ?></li>
            </ul>
        </div>
        <div class="block-reward-membership block-reward-premium-membership">
            <h4 class="block-header  block-header-premium">
                <span><?= $block->escapeHtml(__('Priority Member')) ?></span>
            </h4>
            <ul class="gold-membership-ul-wrapper">
                <li><?= $block->escapeHtml(__('Transaksi > Rp10.000.000')) ?></li>
                <li><?= $block->escapeHtml(__('Birthday Rewards (bonus hingga 100.000 points)')) ?></li>
                <li><?= $block->escapeHtml(__('Bonus Double Point Rewards* (khusus event tertentu)')) ?></li>
                <li><?= $block->escapeHtml(__('Exclusive Invitation Launching Product & Promo')) ?></li>
                <li><?= $block->escapeHtml(__('Diskon Aksesoris Up To 10%')) ?></li>
                <li><?= $block->escapeHtml(__('Membership Baru (Bonus 20.000 points)')) ?></li>
                <li><?= $block->escapeHtml(__('Berlaku Seumur Hidup')) ?></li>
            </ul>
        </div>
    </div>
</div>
