<?php
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';
    $viewMode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';

    $widget_type = $this->getData('widget_type');
    if ($widget_type == 'bestsellers') {
        $items = $block->getBestSellersCollection()->getItems();
    } elseif ($widget_type == 'newproducts') {
        $items = $block->getNewProductsCollection()->getItems();
    } elseif ($widget_type == 'featuredcategory') {
        $items = $block->getFeaturedCategoryProductsCollection()->getItems();
    } elseif ($widget_type == 'saleproducts') {
        $items = $block->getSaleProductsCollection()->getItems();
    } elseif ($widget_type == 'customproducts') {
        $items = $block->getCustomProductsCollection()->getItems();
    } else {
        $items = $block->getProductCollection()->getItems();
    }

    $showWishlist = true;
    $showCompare = true;
    $mailtofriend_btn = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showDescription = false;
    $imageDisplayArea = 'category_page_grid';

    /** @var \Kemana\AcceleratorBase\Helper\Data $kemanaAcceleratorBaseHelper */
    $kemanaAcceleratorBaseHelper = $this->helper(Kemana\AcceleratorBase\Helper\Data::class);
    /** @var \Kemana\Labelmanager\Helper\Data $labelmanagerHelper */
    $labelmanagerHelper = $this->helper(Kemana\Labelmanager\Helper\Data::class);
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $widget_id = $block->getData('widget_id');
    $type_price = 'widget-product-grid-' . $widget_id;

    /** @var \Kemana\AcceleratorBase\Helper\FrontHelper $front_helper */
    $front_helper = $this->helper(Kemana\AcceleratorBase\Helper\FrontHelper::class);
    $productsPerRow = $block->getProductsPerRow();
    $pos = $block->getPositioned();
    /** @var \Magento\Framework\Pricing\Helper\Data $priceHelper */
    $priceHelper = $this->helper(Magento\Framework\Pricing\Helper\Data::class);

    switch ($productsPerRow) {
        case 1:
            $productsPerRow = 'one-column';
            break;
        case 2:
            $productsPerRow = 'two-columns';
            break;
        case 3:
            $productsPerRow = 'three-columns';
            break;
        case 4:
            $productsPerRow = 'four-columns';
            break;
        case 5:
            $productsPerRow = 'five-columns';
            break;
        case 6:
            $productsPerRow = 'six-columns';
            break;
    }

    ?>
    <div class="block widget block-products-list widget-kemana-grid <?php /* @escapeNotVerified */ echo $viewMode; ?>" id="widget-products-<?php echo $widget_id; ?>">
        <?php if ($title):?>
            <div class="widget-title">
                <h2><?php /* @escapeNotVerified */ echo $title; ?></h2>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class=" products-<?php /* @escapeNotVerified */ echo $viewMode; ?> <?php /* @escapeNotVerified */ echo $viewMode . ' ' . $type . ' ' . $productsPerRow; ?>">
                <?php if($labelmanagerHelper->isEnabled('')): ?>
                    <div id="ns-label-loader" data-mage-init='{"nsLabels": {
                    "id": false,
                    "location":"inner",
                    "baseUrl": "<?= $block->getBaseUrl() ?>",
                    "currency": "<?= $kemanaAcceleratorBaseHelper->getCurrencySymbol() ?>"}}'></div>
                <?php endif; ?>
                <ol class="products list items product-items row">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_product): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>

                        <a class="product-url" href="<?= $block->escapeUrl($_product->getProductUrl($_product)) ?>">

                        <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        

                            <?php if ($block->getWishlistHelper()->isAllow()) : ?>
                                <a href="#"
                                   class="action towishlist"
                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                   aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>'
                                   data-action="add-to-wishlist"
                                   role="button">
                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                </a>
                            <?php endif; ?>


                            <?php if ($block->getAddToCompareUrl() && $showCompare) :?>
                                <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>'
                                       title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                </a>
                            <?php endif; ?>


                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image?>
                            <div class="image-wrapper">
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                   class="product photo product-item-photo"
                                   tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                </a>
                            </div>

                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>

                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php if ($_product->isAvailable()) :?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                            <?php if ($_product->isSaleable()) :?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                                      action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                      method="post">
                                                    <input type="hidden"
                                                           name="product"
                                                           value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else :?>
                                                <?php if ($_product->isAvailable()) :?>
                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else :?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription) :?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                               title="<?= /* @noEscape */ $_productNameStripped ?>"
                                               class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        </a>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml(); ?>
        </div>
    </div>
<?php endif;?>
