<?php

/**
 * Copyright © 2022 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Kemana
 * @package  Kemana_CustomerMembership
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Achintha Madushan <amadushan@kemana.com>
 */

/** @var \Kemana\CustomerMembership\Block\Membership\Badge $block */
?>

<div class="membership-batch-area">
    <?php
    echo $block->getCustomerMembershipBadge();
    ?>
</div>

