<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="maintenance-container">
    <div class="maintenance">
        <div class="logo"><img src="images/logo.svg" alt="Planet Gadget"/></div>
        <h1>Maaf, Situs sedang dalam Perbaikan.</h1>
        <p>Kami akan kembali memberikan Anda pengalaman berbelanja yang tak terlupakan.</p>
        <div class="contact-details">
            Bila Anda membutuhkan bantuan, hubungi kami di: <br/>
            <div class="contact-links">
                Email: <a href="mailto:cs@fossil.co.id">cs@planetgadget.store</a> / WhatsApp <a href="https://wa.me/628113988888" target="_blank">0811 3988 888</a>
            </div>
        </div>
    </div>
</div>
<div class="maintenance-footer">
    <div class="footer-text">Copyright © 2022 PlanetGadget.store. All Rights Reserved</div>
</div>
