<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_item = $block->getItem() ?>
<?php
/** @var \Magento\Catalog\Helper\Image $imageHelper */
$imageHelper  = $this->helper(Magento\Catalog\Helper\Image::class);
$image_url = $imageHelper->init($_item->getOrderItem()->getProduct(), 'thumbnail', ['type'=>'thumbnail'])->keepAspectRatio(true)->resize('135', '135')->getUrl();
$prevOptionId = '';
?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>">
        <div class="image"><img src="<?= $image_url ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"></div>
        <div class="item-details">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php foreach($_item->getOrderItem()->getChildrenItems() as $bundleItem):
            $attributes = $block->getSelectionAttributes($bundleItem) ?>
            <?php if (isset($attributes['option_id'])) : ?>
            <?php if ($prevOptionId != $attributes['option_id']) : ?>
                <strong class="bundle-product-option-label"><?= $block->escapeHtml($attributes['option_label']); ?> : </strong>
                <span class="bundle-product-option-value"><?= $block->escapeHtml($bundleItem->getName()); ?></span><br/>
            <?php $prevOptionId = $attributes['option_id'] ?>
            <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($_options = $block->getItemOptions()) : ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()) : ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                        <?= $block->escapeHtml($_formatedOptionValue['value']) ?>
                        <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                        <div class="tooltip content">
                            <dl class="item options">
                                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                            </dl>
                        </div>
                        <?php endif; ?>
                    </dd>
                <?php else : ?>
                    <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        </div>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>"><?= $block->escapeHtml($_item->getSku()) ?></td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>"><?= (int) $_item->getQty() ?></td>
</tr>
