<?php


/** @var \Kemana\Blog\Block\Sidebar\MostView $block */

$posts = $block->getMostViewPosts();
$postsRecent = $block->getRecentPost();
?>
<?php
    /** @var \Kemana\BlogArticle\Helper\Data $kemanaBlogArticleHelper */
    $kemanaBlogArticleHelper = $this->helper(Kemana\BlogArticle\Helper\Data::class);
?>
<div class="mp-sidebar product info detailed">
    <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
        <div class="data item title" data-role="collapsible" id="tab-label-popular">
            <a class="data switch" tabindex="-1" data-toggle="switch" id="tab-label-popular-title">
                <div><?= $block->escapeHtml(__('Popular')) ?></div>
            </a>
        </div>
        <div class="data item content" id="tab-content-popular" data-role="content">
            <?php if ($posts->getSize()): ?>
                <?php foreach ($posts as $post): ?>
                    <div class="list-post-tabs">
                        <div class="post-left">
                            <a href="<?= $post->getUrl() ?>">
                                <img class="img-responsive"
                                     src="<?= $block->resizeImage($post->getImage(), '100x'); ?>">
                            </a>
                        </div>
                        <div class="post-right">
                            <a href="<?= $post->getUrl() ?>"><span><?= $post->getName() ?></span></a>
                            <span class="create-at">
                                <?= $post->getPublishDate() ? $kemanaBlogArticleHelper->getTimeAccordingToTimeZone($post->getPublishDate(), 'd M Y') : ''; ?>
                            </span>
                        </div>
                        <div class="mp-clear"></div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="mostview-nopost"><?= $block->escapeHtml(__('No Posts')); ?></div>
            <?php endif; ?>
        </div>

        <div class="data item title" data-role="collapsible" id="tab-label-mostview">
            <a class="data switch" tabindex="-1" data-toggle="switch" id="tab-label-mostview-title">
                <div><?= $block->escapeHtml(__('Latest')) ?></div>
            </a>
        </div>
        <div class="data item content" id="tab-content-mostview" data-role="content">
            <?php if ($postsRecent->getSize()): ?>
                <?php foreach ($postsRecent as $post): ?>
                    <div class="list-post-tabs" href="<?= $post->getUrl() ?>">
                        <div class="post-left">
                            <a href="<?= $post->getUrl() ?>">
                                <img class="img-responsive"
                                     src="<?= $block->resizeImage($post->getImage(), '100x') ?>">
                            </a>
                        </div>
                        <div class="post-right">
                            <a href="<?= $post->getUrl() ?>"><span><?= $post->getName() ?></span></a>
                            <span class="create-at">
                                <?= $post->getPublishDate() ? $kemanaBlogArticleHelper->getTimeAccordingToTimeZone($post->getPublishDate(), 'd M Y') : ''; ?>
                            </span>
                        </div>
                        <div class="mp-clear"></div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="mostview-nopost"><?= $block->escapeHtml(__('No Posts')); ?></div>
            <?php endif; ?>
        </div>
    </div>
</div>
