<?php
/**
 * @var $block \Kemana\TopCategories\Block\Widget\CategoryWidget
 */
if ($exist = ($block->getCategoryCollection()->getSize())) {
    $type = 'top-category-items';
    $mode = 'grid';
    $image = 'top_cat_content_widget_grid';
    $title = __('Top Categories');
    $items = $this->getCategoryCollection();
}
?>

<?php if ($exist): ?>
    <div class="block widget block-top-cat <?= /* @escapeNotVerified */ $mode ?>">
        <div class="block-title">
            <h2 role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></h2>
        </div>
        <div class="block-content">
            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
            <div class="products-grid products-<?= /* @escapeNotVerified */ $mode ?> <?= /* @escapeNotVerified */ $mode ?>">
                <ul class="product-items <?= /* @escapeNotVerified */ $type ?>">
                    <?php foreach ($items as $_item):
                        $imageUrl = ($_item->getImageUrl()) ? $_item->getImageUrl() : $block->getImagePlaceholder();
                        ?>
                        <li class="product-item category-item">
                            <a href="<?= $_item->getUrl(); ?>">
                                <div class="category-image">
                                    <?php if ($imageUrl != null): ?>
                                        <img src="<?= $imageUrl; ?>"
                                             alt="<?= $_item->getName(); ?>"/>
                                    <?php endif; ?>
                                </div>
                                <div class="category-name" href="<?= $_item->getUrl(); ?>">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </div>
                                <div class="category-short-description">
                                    <?= $block->escapeHtml($_item->getShortDescription()) ?>
                                </div>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
                <?php if (is_array($block->showViewAllLink())): ?>
                    <?php $data = $block->showViewAllLink() ?>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <a class="action view-all primary" href="<?= $data['link'] ?>"><?= $data['text'] ?></a>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
<?php endif; ?>
