<section class="admin__page-section" id="delivery-date-content">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Pick Up Date Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div id="delivery-date">
            <strong><?= __('Pick Up Date') ?>:</strong>
            <span><?= $block->getDeliveryDate() ?></span>
        </div>
        <div id="delivery-time">
            <strong><?= __('Pick Up Time') ?>:</strong>
            <span><?= $block->getDeliveryTime() ?></span>
        </div>
    </div>
</section>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $('#delivery-date-content').insertAfter($('.order-view-billing-shipping'));
        }
    );
</script>