<?php

/**
 * KS_Logistic
 *
 * @see README.md
 *
 */

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<?php
    $gmapApiKey = $block->getConfig(\KS\Logistic\Helper\Data::GMAP_API_PATH);
?>
<form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getNameBlockHtml() ?>
        <?php $dataHelper = $this->helper('Kemana\Customer\Helper\Data');?>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" name="telephone" value="<?php echo $dataHelper->getTelephone() ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone" readonly>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field country required">
            <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect();?>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
                <select id="city_id" name="city_id" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="validate-select" <?php #echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                   <option value=""><?php /* @escapeNotVerified */ echo __('Please Select City.') ?></option>
                </select>
                <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
            </div>
        </div>
         <div class="field district required">
            <label class="label" for="district"><span><?php /* @escapeNotVerified */ echo __('District') ?></span></label>
            <div class="control">
                 <select id="district_id" name="district_id" title="<?php /* @escapeNotVerified */ echo __('District') ?>" class="validate-select" <?php #echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                   <option value=""><?php /* @escapeNotVerified */ echo __('Please Select District.') ?></option>
                </select>
               <input type="text" name="district" value="<?php #echo $block->escapeHtml($block->getAddress()->getDistrict()) ?>" title="<?php /* @escapeNotVerified */ echo __('District') ?>" class="input-text <?php /* @escapeNotVerified */ #echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('district') ?>" id="district"/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>
        <?php if($gmapApiKey) :?>
            <div class="field map_point required">
                <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Map Point') ?></span></label>
                <div class="control">
                    <input type="text" name="map_point" value="<?php echo $block->getAddress()->getCustomAttribute('map_point') ? $block->getAddress()->getCustomAttribute('map_point')->getValue() : null ?>" title="<?php /* @escapeNotVerified */ echo __('Map Point') ?>" id="map_point" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('map_point') ?>">
                </div>
            </div>
            <div class="pinpoint actions-toolbar">
                <div class="primary">
                    <button type="button" class="action save go-popup" title="<?php /* @escapeNotVerified */ echo __('Choose Map Point') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Choose Map Point') ?></span>
                    </button>
                </div>
            </div>
        <?php endif;?>


        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice checkbox set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?></div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice checkbox set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping"><span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<?php if($gmapApiKey) :?>
    <div id="gosend-popup-modal" style="display: none;">
        <span class="subtitle"><?= __('Please make sure your pinned point in map match with your address.'); ?></span>
        <div class="autocompletegosendwrap">
            <input id="autocompleteGosend" placeholder="<?= __('Find address or location'); ?>" type="text" autocomplete="off" />
            <i class="fa fa-search"></i>
        </div>
        <div id="map-gosend">
            Powered by Google Map
        </div>

        <div class="location-name-wrap">
            <input id="location-name" type="text" autocomplete="off" />
            <i class="fa fa-map-marker-alt"></i>
        </div>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $gmapApiKey ?>&libraries=places" type="text/javascript"></script>
    <script type="text/javascript">
        require([
            'jquery',
            'KS_Logistic/js/popupmaps'
        ], function ($,openmap) {
            'use strict';
            $(".go-popup, #map_point").on('click', function(){
                openmap({content:$('#gosend-popup-modal'), targetInput: '#map_point', targetMap: 'map-gosend', autocompleteGosend: 'autocompleteGosend', locationName: '#location-name'});
            });

        });
    </script>
<?php endif;?>

<?php
    $cityId = $block->getAddress()->getCustomAttribute('city_id');
    $districtId = $block->getAddress()->getCustomAttribute('district_id');
    $districtText = $block->getAddress()->getCustomAttribute('district');
?>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>,
                "defaultCityId": "<?php /* @escapeNotVerified */ echo $cityId ? $cityId->getValue():null ?>",
                "cityJson": <?php /* @escapeNotVerified */ echo $this->helper('KS\Logistic\Helper\Data')->getCitiesJson() ?>,
                "cityListId": "#city_id",
                "cityInputId": "#city",
                "defaultCityInput": "<?php /* @escapeNotVerified */ echo $block->getAddress()->getCity() ?>",
                "defaultDistrictId": "<?php /* @escapeNotVerified */ echo $districtId ? $districtId->getValue():null ?>",
                "districtJson": <?php /* @escapeNotVerified */ echo $this->helper('KS\Logistic\Helper\Data')->getDistrictJson() ?>,
                "districtListId": "#district_id",
                "districtInputId": "#district",
                "defaultDistrictInput": "<?php /* @escapeNotVerified */ echo $districtText ? $districtText->getValue():null ?>"
            }
        }
    }
</script>
