<?php


/** @var \Kemana\Blog\Block\MonthlyArchive\Widget $block */

$dateArrayCount = $block->getDateArrayCount();
$dateArrayUnique = $block->getDateArrayUnique();
$dateLabel = $block->getDateLabel();

if ($block->isEnable() && $dateArrayUnique): ?>
    <div class="mp-sidebar mpcss">
        <div class="block-title sidebar-archives">
            <h6 class="block-mp-sidebar-heading" role="heading"
               aria-level="2"><?= $block->escapeHtml(__('Monthly Archive')) ?></h6>
        </div>
        <div class="mpcss-content-wrapper menu-archives">
            <ul class="menu-archives">
                <?php for ($i = 0; $i < $block->getDateCount(); $i++): ?>
                    <li class="archive-item">
                        <a class="list-archives"
                           href="<?= $block->getMonthlyUrl(date("Y-m", $this->dateTime->timestamp($dateArrayUnique[$i]))) ?>">
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                            <span class="month"><?= $dateLabel[$i]; ?></span><span class="count"><?= '(' . $dateArrayCount[$i] . ')'; ?></span>
                        </a>
                    </li>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
