<?php


/** @var \Kemana\Blog\Block\Widget\Posts $block */

$posts = $block->getCollection();
$title = __('News & <span>Updates</span>');
?>
<div class="post-list-wrapper">
    <div class="post-list-inner-container">
        <div class="blog-widget-title widget-title block-title">
            <h2><?= /* @escapeNotVerified */ $title ?></h2>
        </div>
        <span><a href="<?= $block->getBlogUrl(''); ?>"><?= $block->escapeHtml(__('See more')) ?></a></span>
        <div class="post-list-container mpcss" id="mpblog-list-container">
            <div class="widget-title">
                <a href="<?= $block->getBlogUrl(''); ?>"><?= $block->getTitle(); ?></a>
            </div>
            <div class="row">
                <?php foreach ($posts as $post): ?>
                    <div class="col-md-4 col-12 post-list-item">
                        <div class="post-item-wrapper">
                            <?php if ($post->getImage()): ?>
                                <div class="post-image">
                                    <a href="<?= $post->getUrl() ?>">
                                        <img class="img-responsive"
                                             src="<?= $block->resizeImage($post->getImage(), '400x'); ?>"
                                             alt="<?= $block->escapeHtml($post->getName()); ?>"/>
                                    </a>
                                </div>
                            <?php endif; ?>
                            <div class="post-info-wrapper">
                                <h2 class="mp-post-title">
                                    <a class="post-link-title" title="<?= $post->getName(); ?>"
                                       href="<?= $post->getUrl() ?>">
                                        <?= $post->getName(); ?>
                                    </a>
                                </h2>
                                <div class="mp-post-info">
                                    <?= $block->getPostInfo($post) ?>
                                </div>
                                <div class="post-short-description">
                                    <p><?= $post->getShortDescription(); ?></p>
                                </div>
                                <div class="mp-clearfix"></div>
                                <div class="mp-post-meta-info mp-alignright">
                                    <div class="actions">
                                        <a class="mp-read-more" href="<?= $post->getUrl(); ?>"
                                           title="<?= $block->escapeHtml(__('Read More')); ?>"><?= $block->escapeHtml(__('Read more')); ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
