<?php

?>
<?php if ($block->isBlogEnabled()): ?>
    <div class="field choice mp-blog-sign-up-author">
        <input type="checkbox" name="is_mp_author" title="<?= /* @noEscape */
        $block->escapeHtml(__('Sign Up to be an Author')) ?>" value="1" id="is_mp_author" class="checkbox">
        <label for="is_mp_author" class="label"><span><?= /* @noEscape */
                $block->escapeHtml(__('Sign Up to be an Author')) ?></span></label>
    </div>
<?php endif; ?>
