<?php


/** @var \Kemana\Blog\Block\Author\Widget $block */

$author = $block->getCurrentAuthor();
if ($author): ?>
    <div class="mp-sidebar mpcss">
        <div class="author-name col-xs-12">
            <h3><?= $author->getName() ?></h3>
        </div>
        <div class="author-image col-xs-12">
            <img class="img-responsive"
                 src="<?= ($author->getImage()) ? $block->resizeImage($author->getImage(), '135x', \Kemana\Blog\Helper\Image::TEMPLATE_MEDIA_TYPE_AUTH) : $block->getDefaultAuthorImage(); ?>"
                 alt="<?= $block->escapeHtml($author->getName()); ?>"/>
        </div>
        <div class="author-content col-xs-12">
            <?= $block->getPageFilter(($author->getShortDescription())) ? $block->getPageFilter(($author->getShortDescription())) : 'No info'; ?>
        </div>
        <div class="author-social col-xs-12">
            <?php if ($author->getFacebookLink()): ?>
                <a href="<?= $author->getFacebookLink() ?>" target="_blank">
                    <img style="width: unset;"
                         src="<?= $this->getViewFileUrl('Kemana_Blog::media/images/facebook.png') ?>"
                         align="middle"
                         alt="<?= $block->escapeHtml($author->getName()); ?>"/>
                </a>
            <?php else: ?>
                <img style="width: unset;"
                     src="<?= $this->getViewFileUrl('Kemana_Blog::media/images/facebookoff.png') ?>"
                     align="middle"
                     alt="<?= $block->escapeHtml($author->getName()); ?>"/>
            <?php endif; ?>
            <?php if ($author->getTwitterLink()): ?>
                <a href="<?= $author->getTwitterLink() ?>" target="_blank">
                    <img style="width: unset;"
                         src="<?= $this->getViewFileUrl('Kemana_Blog::media/images/twitter.png') ?>"
                         align="middle"
                         alt="<?= $block->escapeHtml($author->getName()); ?>"/>
                </a>
            <?php else: ?>
                <img style="width: unset;"
                     src="<?= $this->getViewFileUrl('Kemana_Blog::media/images/twitter-off.png') ?>"
                     align="middle"
                     alt="<?= $block->escapeHtml($author->getName()); ?>"/>
            <?php endif; ?>
            <div class="mp-clear"></div>
        </div>
        <div class="author-border col-xs-12"></div>
    </div>
<?php endif; ?>
