# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.4
    disk: 5120

redis:
    type: redis:6.0

elasticsearch:
    type: elasticsearch:7.10
    disk: 1024
