<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php $parentItem = $block->getItem() ?>

<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $block->getChildren($parentItem) ?>
<?php $_item = $parentItem->getOrderItem() ?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper(Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()) : ?>
    <?php $_showlastRow = true ?>
<?php else : ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

    <tr class="bundle-item bundle-parent">
        <td class="item-info">
            <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
            <?php foreach ($items as $_item) : ?>
                <?php if ($_item->getParentItem()) : ?>
                <?php $attributes = $block->getSelectionAttributes($_item) ?>
                    <?php if (isset($attributes['option_id'])) : ?>
                    <?php if ($_prevOptionId != $attributes['option_id']) : ?>
                        <strong class="bundle-product-option-label"><?= $block->escapeHtml($attributes['option_label']); ?> : </strong>
                        <span class="bundle-product-option-value"><?= $block->escapeHtml($_item->getName()); ?></span> <br/>
                        <?php $_prevOptionId = $attributes['option_id'] ?>
                    <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </td>
        <td class="item-qty">
            <?php if (($block->isShipmentSeparately() && $_item->getParentItem()) || (!$block->isShipmentSeparately())) : ?>
                <?php if (isset($shipItems[$_item->getParentItem()->getId()])) : ?>
                    <?= (float)$shipItems[$_item->getParentItem()->getId()]->getQty() * 1 ?>
                <?php elseif ($_item->getIsVirtual()) : ?>
                    <?= $block->escapeHtml(__('N/A')) ?>
                <?php else : ?>
                    0
                <?php endif; ?>
            <?php else : ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>

<?php if ($_showlastRow) : ?>
    <tr>
        <td colspan="2" class="item-extra">
            <?php if ($block->getItemOptions()) : ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                            <dd><?= $block->escapeHtml($option['value']) ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif; ?>
