<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<div class="block block-balance">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Current Balance')) ?></strong>
    </div>
    <div class="block-content">
        <p>
            <?= /* @noEscape */ $this->helper(Magento\Framework\Pricing\Helper\Data::class)->currency($block->getBalance()) ?>
        </p>
    </div>
</div>
