<?php
/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>

<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Address')) ?></strong></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>

            <div class="table-wrapper additional-addresses">
                <?php foreach ($_pAddsses as $address) : ?>
                <?php if (!$address->isDefaultShipping() && !$address->isDefaultBilling()): ?>
                        
                    <div class="box box-content address-box-content">
                        <address>
                            <?= $this->getLayout()->getBlock('address_book')->getAddressHtml($address) ?>
                            <br/>
                            <?php
                                $mapPoint = $block->getAddressMapPoint($block->getAddressById($address->getId()));
                            ?>
                            <span class="map-point-label <?=($mapPoint === 'Already Pinpoint') ? 'active' : ''?>">
                                <?= $block->escapeHtml(__($mapPoint)) ?>
                            </span>
                        </address>
                        <div class="box-actions">
                            <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                            <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"><span><?= $block->escapeHtml(__('Make default address')) ?></span></a>
                            <a class="action delete" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>"><span><?= $block->escapeHtml(__('Remove')) ?></span></a>
                        </div>
                    </div>
                    <?php else : ?>
                        <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
                    <?php endif ?>
                <?php endforeach; ?>
            </div>

        <?php endif ?>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "div a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
