<?php


$tree = $block->getTree();
if ($tree):
    ?>
    <div class="mp-sidebar mpcss" style="display: none;">
        <div class="block-title col-xs-12 sidebar-categories">
            <span class="block-mp-sidebar-heading blog-sidebar-heading"><?= $block->escapeHtml(__('Categories')) ?></span>
        </div>
        <div class="mpcss-content-wrapper menu-categories">
            <?= $block->getCategoryTreeHtml($tree) ?>
        </div>
    </div>
    <script type="text/javascript">
        require(['Kemana_Blog/js/categorytree'], function () {
        });
    </script>
<?php endif; ?>
 