<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
$viewModel = $block->getViewModel();
$qtyCount = $viewModel->getQtyCount();
$helper = $this->helper(Kemana\MsDynamics\Helper\Data::class);
?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) : ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    <script type="text/x-magento-init">
                        {
                            "#custom-qty": {
                                "Magento_Ui/js/core/app": {
                                    "components": {
                                        "qty-counter": {
                                            "component": "qty-counter",
                                            "config": {
                                                "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                            }
                                        }
                                     }
                                }
                            }
                        }
                    </script>
                </div>
            </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

</script>
<?php if($_product->getTypeId() === 'simple'):?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Kemana_MsDynamics/js/update-stock": {
                "url" : "<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl().'msdynamic/stock/UpdateStock')) ?>",
                "productid": <?= $_product->getId() ?>,
                "producttype": "<?= $_product->getTypeId() ?>"
            }
        }
    }
</script>
<?php endif;?>